[package]
name = "simple_asn1"
version = "0.4.1"
authors = ["Adam Wick <awick@uhsure.com>"]
description = "A simple DER/ASN.1 encoding/decoding library."
categories = ["encoding"]
keywords = ["ASN1","encoding","DER"]
license = "ISC"
repository = "https://github.com/acw/simple_asn1"

[dependencies]
chrono     = "^0.4.0"
num-bigint = "^0.2.0"
num-traits = "^0.2.0"

[dev-dependencies]
quickcheck = "^0.7.1"
rand = "0.5.5"
